services:
  - type: web
    name: bubblescan-api
    env: python
    buildCommand: |
      cd frontend-react
      npm ci
      npm run build
      cd ..
      pip install -r requirements.txt
    startCommand: cd scanner-comunidade && uvicorn api:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false